const mongoose = require('mongoose');
const Product = require('./models/productModel');
const User = require('./models/userModel');
require('dotenv').config();

// Sample products with more data for each category
const products = [
  // Category: men
  {
    name: 'Men\'s Casual Shirt',
    price: 1999,
    description: 'A stylish casual shirt for men.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'men',
    countInStock: 10,
    numReviews: 0,
    rating: 4.5,
    discount: 10,
    isOnSale: true,
    featured: true,
  },
  {
    name: 'Men\'s Denim Jacket',
    price: 3499,
    description: 'A rugged denim jacket for men.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'men',
    countInStock: 7,
    numReviews: 0,
    rating: 4.3,
    discount: 5,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Men\'s Formal Trousers',
    price: 2499,
    description: 'Elegant formal trousers for men.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'men',
    countInStock: 12,
    numReviews: 0,
    rating: 4.0,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Men\'s Sports Shoes',
    price: 3999,
    description: 'Comfortable sports shoes for men.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'men',
    countInStock: 15,
    numReviews: 0,
    rating: 4.7,
    discount: 15,
    isOnSale: true,
    featured: true,
  },
  {
    name: 'Men\'s Leather Belt',
    price: 999,
    description: 'A durable leather belt for men.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'men',
    countInStock: 20,
    numReviews: 0,
    rating: 4.2,
    discount: 0,
    isOnSale: false,
    featured: false,
  },

  // Category: women
  {
    name: 'Women\'s Elegant Dress',
    price: 2999,
    description: 'An elegant dress for women.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'women',
    countInStock: 8,
    numReviews: 0,
    rating: 4.8,
    discount: 15,
    isOnSale: true,
    featured: true,
  },
  {
    name: 'Women\'s Casual Top',
    price: 1499,
    description: 'A comfortable casual top for women.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'women',
    countInStock: 10,
    numReviews: 0,
    rating: 4.4,
    discount: 10,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Women\'s High Heels',
    price: 2799,
    description: 'Stylish high heels for women.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'women',
    countInStock: 6,
    numReviews: 0,
    rating: 4.6,
    discount: 5,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Women\'s Handbag',
    price: 1999,
    description: 'A chic handbag for women.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'women',
    countInStock: 12,
    numReviews: 0,
    rating: 4.3,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Women\'s Sunglasses',
    price: 1299,
    description: 'Trendy sunglasses for women.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'women',
    countInStock: 15,
    numReviews: 0,
    rating: 4.1,
    discount: 0,
    isOnSale: false,
    featured: false,
  },

  // Category: girl
  {
    name: 'Girls\' Party Dress',
    price: 1499,
    description: 'A cute party dress for girls.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'girl',
    countInStock: 15,
    numReviews: 0,
    rating: 4.2,
    discount: 5,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Girls\' School Uniform',
    price: 999,
    description: 'A comfortable school uniform for girls.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'girl',
    countInStock: 20,
    numReviews: 0,
    rating: 4.0,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Girls\' Sneakers',
    price: 1299,
    description: 'Cute sneakers for girls.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'girl',
    countInStock: 18,
    numReviews: 0,
    rating: 4.3,
    discount: 10,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Girls\' Hairband',
    price: 299,
    description: 'A stylish hairband for girls.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'girl',
    countInStock: 25,
    numReviews: 0,
    rating: 4.1,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Girls\' Jacket',
    price: 1799,
    description: 'A warm jacket for girls.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'girl',
    countInStock: 10,
    numReviews: 0,
    rating: 4.4,
    discount: 5,
    isOnSale: true,
    featured: false,
  },

  // Category: boy
  {
    name: 'Boys\' Sports Kit',
    price: 1299,
    description: 'A sports kit for boys.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'boy',
    countInStock: 12,
    numReviews: 0,
    rating: 4.0,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Boys\' Casual T-Shirt',
    price: 799,
    description: 'A comfy t-shirt for boys.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'boy',
    countInStock: 15,
    numReviews: 0,
    rating: 4.2,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Boys\' Jeans',
    price: 1199,
    description: 'Stylish jeans for boys.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'boy',
    countInStock: 10,
    numReviews: 0,
    rating: 4.1,
    discount: 5,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Boys\' Backpack',
    price: 899,
    description: 'A durable backpack for boys.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'boy',
    countInStock: 20,
    numReviews: 0,
    rating: 4.3,
    discount: 0,
    isOnSale: false,
    featured: false,
  },
  {
    name: 'Boys\' Running Shoes',
    price: 1499,
    description: 'Lightweight running shoes for boys.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'boy',
    countInStock: 12,
    numReviews: 0,
    rating: 4.5,
    discount: 10,
    isOnSale: true,
    featured: false,
  },

  // Category: Wedding
  {
    name: 'Wedding Lehenga',
    price: 5999,
    description: 'A beautiful wedding lehenga.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'Wedding',
    countInStock: 5,
    numReviews: 0,
    rating: 4.9,
    discount: 20,
    isOnSale: true,
    featured: true,
  },
  {
    name: 'Wedding Sherwani',
    price: 7999,
    description: 'A traditional sherwani for weddings.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'Wedding',
    countInStock: 4,
    numReviews: 0,
    rating: 4.8,
    discount: 15,
    isOnSale: true,
    featured: true,
  },
  {
    name: 'Wedding Jewelry Set',
    price: 3999,
    description: 'A stunning jewelry set for weddings.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'Wedding',
    countInStock: 8,
    numReviews: 0,
    rating: 4.7,
    discount: 10,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Wedding Dupatta',
    price: 1999,
    description: 'An elegant dupatta for wedding attire.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'Wedding',
    countInStock: 10,
    numReviews: 0,
    rating: 4.5,
    discount: 5,
    isOnSale: true,
    featured: false,
  },
  {
    name: 'Wedding Kurta Set',
    price: 4999,
    description: 'A festive kurta set for weddings.',
    image: '/api/placeholder/400/300',
    brand: 'Trendify',
    category: 'Wedding',
    countInStock: 6,
    numReviews: 0,
    rating: 4.6,
    discount: 10,
    isOnSale: true,
    featured: false,
  },
];

const seedProducts = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Find the admin user
    const adminUser = await User.findOne({ email: '0022abhinav@gmail.com' });
    if (!adminUser) {
      console.error('Admin user with email 0022abhinav@gmail.com not found. Please create this user first.');
      process.exit(1);
    }
    console.log('Found admin user:', adminUser.email);

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Add the user ID to each product
    const productsWithUser = products.map(product => ({
      ...product,
      user: adminUser._id, // Assign the admin user's ID to the product
    }));

    // Insert sample products
    await Product.insertMany(productsWithUser);
    console.log('Inserted sample products');

    console.log('Database seeded successfully');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedProducts();